- hosts: all
  tasks: 
    
  - name: Activa el servido de nginx
    shell: service nginx start
    
  - name: instalar git 
    apt:
      name: git
      state: present
      update_cache: yes
      
    - name: Clonar repositorio
      shell: git clone https://github.com/oscar13545/balanceo-de-cargas.git
      
     - name: Instalar los paquetes de docker
    remote_user: ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      
  - name: Generar las llaves
    remote_user: ubuntu
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      
  - name: Verificar donde se encuentran las llaves
    remote_user: ubuntu
    apt_key:
      id: 0EBFCD88
      state: present
      
  - name: Colocar los repositorios
    remote_user: ubuntu
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
      
  - name: Comando apt update, actualizar paquetes
    remote_user: ubuntu
    apt:
      update_cache: yes
      
  - name: Instalar docker
    remote_user: ubuntu
    apt:
      name: docker-ce
      state: present
      update_cache: yes
      
  - name: Anadir el usuario ubuntu para que pueda usar los docker y arreglar problema de permisos
    remote_user: ubuntu
    user:
      name: "ubuntu"
      group: "docker"
      append: yes
      
  - name: Instalar docker-compose
    remote_user: ubuntu
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

    - name: Correr el archivo Dockerfile
      shell: cd balanceo-de-cargas && docker-compose up
